### ISSUE TITLE
pkix does not build reproducibly

### ISSUE THREAD

**Issue by debalance** [processone/pkix#1]
Hi,
it looks like the build time path ends up in the beam files, thus pkix does not build reproducibly:
https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/erlang-p1-pkix.html

The other p1 packages don't have this problem.

**Comment by badlop** [comment]
Looking at https://tests.reproducible-builds.org/debian/issues/unstable/captures_build_path_in_beam_files_issue.html there are many other erlang packages (many related to ejabberd) that have the same issue.

Looking at the [erlang compile documentation](http://erlang.org/doc/man/compile.html#file-2), it appears that the solution would be to compile the beam files using the 'deterministic' option:

> deterministic
>     Omit the options and source tuples in the list returned by Module:module_info(compile), and reduce the paths in stack traces to the module name alone. This option will make it easier to achieve reproducible builds.

> The other p1 packages don't have this problem.

Are you sure only pkix triggers that problem? In the original source code of pkix and other p1 repositories, their rebar.config files have no significant difference, and no mention to that 'deterministic' option. Maybe that option was added to some p1 packages in debian, in order to solve that issue, and only pkix lacks it?

**Comment by debalance** [comment]
Ah sorry, you're right, it's a common issue. It's only pkix that failed to build from source completely due to a missing build dependency, but I have corrected that a few days ago.

**Comment by badlop** [comment]
The fix is as simple as adding a line to rebar.config of all the packages, but I don't know about the implications:

```diff
diff --git a/rebar.config b/rebar.config
index 77a7290..9603618 100644
--- a/rebar.config
+++ b/rebar.config
@@ -17,6 +17,7 @@
 %%%-------------------------------------------------------------------
 
 {erl_opts, [debug_info,
+	    deterministic,
 	    {src_dirs, ["src"]}]}.
 
 {cover_enabled, true}.

```

**Comment by zinid** [comment]
Is this considered resolved?

**Comment by mremond** [comment]
And if resolved, should we apply that patch ?

**Comment by debalance** [comment]
The deterministic flag makes the build (more) reproducible indeed.

@weiss found out that I can also add "export ERL_COMPILER_OPTIONS=deterministic" to my debian/rules makefiles, rebar accepts and does not override that.

So I leave it up to you if you want to add the deterministic flag to all your rebar.config(.script)s etc.,
I have already added the above line to all my Debian packages.
